# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx pylint
        pip install -r requirements.txt
    - name: setup
      run: |
        groupadd group_foo
        groupadd group_bar
        useradd -m -G users,group_foo,group_bar pav_test
        ln -s pavilion.yaml.ci test/data/pav_config_dir/pavilion.yaml
        echo "working_dir: $(pwd)/test/working_dir" >> test/data/pav_config_dir/pavilion.yaml
        echo "spack_path: $(pwd)/test/spack" >> test/data/pav_config_dir/pavilion.yaml
        ./test/utils/spack_setup test
        chown -R pav_test /root/project
        chmod o+rx /root/project
    - name: run_tests
      run: | 
        su pav_test -c "/root/project/test/run_tests"
